obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.165, -0.035], [-0.165, 0.035], [0.038, 0.165], [0.118, 0.118], [0.118, -0.118], [0.038, -0.165]]
#robot_radius: ir_of_robot
inflation_radius: 0.005
cost_scaling_factor: 10.0

#observation_sources: 