global_costmap:
  global_frame: map
  robot_base_frame: r1/base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true

local_costmap:
  global_frame: r1/odom
  robot_base_frame: r1/base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 1.0
  height: 1.0
  origin_x: -0.5
  origin_y: 0.0
  resolution: 0.01
  transform_tolerance: 0.2

  observation_sources: lidar

  lidar: {
    sensor_frame: r1/laser_frame,
    data_type: LaserScan,
    topic: /r1/laser/scan_filtered,
    clearing: true,
    marking: true
  }
  
TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: true