obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.075, 0.130], [0.075, 0.130], [0.075, -0.130], [-0.075, -0.130]]
#robot_radius: ir_of_robot
inflation_radius: 0.005
cost_scaling_factor: 10.0
transform_tolerance: 0.3