r1:
  teleop:
    max_linear_x_velocity: 0.3
    max_linear_y_velocity: 0.3
    max_angular_z_velocity: 3.0
    boost_velocity_ratio: 2.0
    cmd_vel_sources: [cmd_vel_auto, cmd_vel_teleop]

  joy:
    dev: /dev/input/js0
    deadzone: 0.20
    # Hertz
    autorepeat_rate: 20.0
    # Seconds
    coalesce_interval: 0.0

r2:
  teleop:
    max_linear_x_velocity: 0.2
    max_linear_y_velocity: 0.0
    max_angular_z_velocity: 3.0
    boost_velocity_ratio: 2.0
    cmd_vel_sources: [cmd_vel_auto, cmd_vel_teleop]

  joy:
    dev: /dev/input/js0
    deadzone: 0.20
    # Hertz
    autorepeat_rate: 20.0
    # Seconds
    coalesce_interval: 0.0