r2_laser_scan_filter:
    scan_filter_chain:
    - name: bounds_repeat
      type: sd_sensor/LaserScanAngularBoundsListFilter
      params:
        angles: []
        angles2: []


mpu6050:
  frame: 'r2/imu_link'
  bias_gx: 0.162825896087
  bias_gy: -0.123678560658
  bias_gz: 0.0581620980884
  bias_ax: -0.81915744873
  bias_ay: -0.39402782959
  bias_az: 0.0371353930664