r2_laser_scan_filter:
  scan_filter_chain:
  - name: bounds_repeat
    type: sd_sensor/LaserScanAngularBoundsListFilter
    params:
      angles: []
      angles2: []

r2_laser_pattern_detector:
  detector_frequency: 5.0

  # ? = any, 0 = below threshold, 1 = greater than threshold, X = obstructed
  # 
  # Degree              0         60        120       180        240       300       
  isTirette_pattern:   "XXX??????????????????????????????????????????????????????XXX"
  isBackFree_pattern:  "??111???????????????????????????????????????????????????????"
  isLeftFree_pattern:  "??????????????????????????11????????????????????????????????"
  isFrontFree_pattern: "??????????????????????????????11????????????????????????????"
  isRightFree_pattern: "??????????????????????????????????11????????????????????????"
  
  # Distance threshold in meters
  isTirette_threshold: 0.1
  isLeftFree_threshold: 0.3
  isFrontFree_threshold: 0.3
  isRightFree_threshold: 0.3
  isBackFree_threshold: 0.3

mpu6050:
  frame: 'r2/imu_link'
  bias_gx: 0.162825896087
  bias_gy: -0.123678560658
  bias_gz: 0.0581620980884
  bias_ax: -0.81915744873
  bias_ay: -0.39402782959
  bias_az: 0.0371353930664