control_loop:
  loop_hz: 50 # in Hz
  cycle_time_error_threshold: 0.1 # in seconds (Means an 10% error threshold for 100Hz)
  print_state: true   # true to see controller state in console (every second)
  publish_state: true # publish regulator state to topics

hardware_interface:
  is_quadrature_encoder : true
  velocity_controller_enabled : true
  timeout: 1.0 # seconds
  joints: 
    - right_wheel_to_base
    - left_wheel_to_base
    - back_wheel_to_base
  encoder_topics:
    - encoder/right
    - encoder/left
    - encoder/back
  encoder_speed_topics:
    - encoder/right/speed
    - encoder/left/speed
    - encoder/back/speed
  pwm_topics:
    - pwm/right
    - pwm/left
    - pwm/back
  speed_topics:
    - speed/right
    - speed/left
    - speed/back
  pwm_max:
    - 4096
    - 4096
    - 4096
  encoder_steps_for_one_wheel_revolution:
    - 823.0
    - 823.0
    - 823.0
  encoder_speed_steps_for_one_rad_per_second:
    - 7863.0
    - 7863.0
    - 7863.0
  velocity_controllers_velocity_to_pwm: 
    - 60.0  # Unit : if pwm = velocity_controllers_velocity_to_pwm, wheel should rotate at 1 rad/s
    - 60.0
    - 60.0
  velocity_controllers_friction_pwm: 
    - 450.0 # Minimum PWM allowing the wheel to turn
    - 450.0
    - 450.0  
  velocity_controllers_pid_p:
    - 80.0
    - 80.0
    - 80.0
  velocity_controllers_pid_i:
    - 1.0
    - 1.0
    - 1.0
  velocity_controllers_pid_d:
    - 0.0
    - 0.0
    - 0.0

rosserial_server:
  baud: 115200
  port: /dev/ttyUSBMotor
