control_loop:
  loop_hz: 20 # in Hz
  cycle_time_error_threshold: 0.01 # in seconds (Means an 20% error threshold for 20Hz)
  print_state: false # true to see controller state in console (every second)
  publish_state: true # publish regulator state to topics

hardware_interface:
  is_quadrature_encoder : false
  timeout: 1.0 # seconds
  joints: 
    - right_wheel_to_base
    - left_wheel_to_base
  encoder_topics:
    - right/encoder
    - left/encoder
  pwm_topics:
    - right/pwm
    - left/pwm
  pwm_max:
    - 255
    - 255
  encoder_steps_for_one_wheel_revolution:
    - 140.0
    - 140.0
  velocity_controllers_velocity_to_pwm: 
    - 1400.0 # Unit : 1m/s to PWM
    - 1400.0
  velocity_controllers_friction_pwm: 
    - 30.0 # Minimum PWM allowing the wheel to turn
    - 30.0
  velocity_controllers_pid_p:
    - 5.0
    - 5.0
  velocity_controllers_pid_i:
    - 0.005
    - 0.005
  velocity_controllers_pid_d:
    - 0.0
    - 0.0

rosserial_server:
  baud: 57600
  port: /dev/ttyUSB0