ydlidar:
  port: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
  baudrate: 115200
  frame_id: r1/laser_frame
  low_exposure: false
  resolution_fixed: true
  auto_reconnect: true
  reversion: false
  angle_min: -180
  angle_max: 180
  range_min: 0.1
  range_max: 16.0
  ignore_array: ""
  samp_rate: 9
  frequency: 7