<?xml version="1.0"?>
<robot name="r1" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="body_height" value="0.130" />
    <xacro:property name="body_ground_spacing" value="0.01" />
    <xacro:property name="body_wheel_to_center" value="0.175" />

    <xacro:property name="wheel_length" value="0.034" />
    <xacro:property name="wheel_radius" value="0.030" />
    <xacro:property name="wheel_effort_max" value="10000" />
    <xacro:property name="wheel_velocity_max" value="10000" />

    <xacro:include filename="$(find sd_description)/urdf/materials.xacro" />

    <link name="base_link"/>

    <link name="body_link">
        <visual>
            <geometry>
				<mesh filename="package://sd_description/meshes/r1_base.stl" scale="0.000897 0.000897 0.000897"/>
            </geometry>
            <material name="red"/>
            <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        </visual>
        <collision>
            <geometry>
				<mesh filename="package://sd_description/meshes/r1_base.stl" scale="0.000897 0.000897 0.000897"/>
            </geometry>
        </collision>
        <inertial>
			<mass value="4.2"/>
			<inertia ixx="3e-2" ixy="0.0" ixz="0.0" iyy="3e-2" iyz="0.0" izz="4e-2"/>
            <origin xyz="0 0 ${-body_height / 4}" rpy="0 0 0"/>
        </inertial>
    </link>

    <joint name="body_to_base" type="fixed">
        <parent link="base_link"/>
        <child link="body_link"/>
        <origin xyz="0 0 ${- wheel_radius + body_ground_spacing}" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="wheel_macro" params="name angle">
        <link name="${name}_wheel_link">
            <visual>
                <geometry>
				    <mesh filename="package://sd_description/meshes/r1_wheel.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
                </geometry>
            </collision>
	        <inertial>
				<mass value="0.3"/>
				<inertia ixx="2e-4" ixy="0.0" ixz="0.0" iyy="2e-4" iyz="0.0" izz="2.5e-4"/>
	        </inertial>
        </link>

        <joint name="${name}_wheel_to_base" type="continuous">
            <parent link="base_link"/>
            <child link="${name}_wheel_link"/>
            <origin xyz="${body_wheel_to_center * cos(angle)} ${body_wheel_to_center * sin(angle)} 0" rpy="${-pi / 2} 0 ${pi / 2 + angle}"/>
            <limit effort="${wheel_effort_max}" velocity="${wheel_velocity_max}"/>
            <axis xyz="0 0 1"/>
        </joint>
	    
		<transmission name="${name}_wheel_to_base_transmission">
		    <type>transmission_interface/SimpleTransmission</type>
		    <joint name="${name}_wheel_to_base">
				<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		    </joint>
		    <actuator name="${name}_wheel_to_base_actuator">
				<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
		    </actuator>
		</transmission>
    </xacro:macro>

    <wheel_macro name="left" angle="${pi / 3}"/>
    <wheel_macro name="right" angle="${-1 * pi / 3}"/>
    <wheel_macro name="back" angle="${pi}"/>
</robot>
